
package TimeSheet;

import static java.lang.Thread.sleep;
import javax.swing.*;
import java.util.*;
public class TimeSheet extends javax.swing.JFrame{
    Date dt = new Date();
    
    int hours = dt.getHours(), minutes = dt.getMinutes(),
        seconds = dt.getSeconds(), milliSeconds = 0;
    String startTime = "";
    boolean state = true;
    
    /**
     * Creates new form TimeSheet
     */
    public TimeSheet() {
        initComponents();
        runTime();
    }
    
    public void runTime(){
        state = true;
        Thread t;
        t = new Thread(){
            public void run(){
                for(;;){
                    if(state){
                        try{
                            sleep(1);
                            if(milliSeconds > 1000){
                                milliSeconds = 0;
                                seconds++;
                            }
                            
                            if(seconds > 60){
                                milliSeconds = 0;
                                seconds = 0;
                                minutes++;
                            }               
                            if(minutes > 60){
                                milliSeconds = 0;
                                seconds = 0;
                                minutes = 0;
                                hours++;
                            }
                            milliSeconds++;
                            //lblRunningTimeMilliSec.setText(""+milliSeconds);
                            lblHours.setText(""+hours);
                            lblMinute.setText(""+minutes);
                            lblSecond.setText(""+seconds);
                        }catch(InterruptedException error){
                            JOptionPane.showMessageDialog(null, "Error in runTime method","runTime method"+
                            error.getMessage(),JOptionPane.ERROR_MESSAGE);
                        }
                    }else{
                        break;
                    }
                }
            }
        };
        t.start();
        startTime = dt.getHours()+":"+dt.getMinutes()+":"+dt.getSeconds();
        lblStartTime.setText(startTime);
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblLoggedInUser = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btnAmendTimeSheet = new javax.swing.JButton();
        txtDisplayUserTime = new java.awt.TextField();
        lblMinute = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        btnStopTimeSheet = new javax.swing.JButton();
        lblStartTime = new javax.swing.JLabel();
        lblStopTime = new javax.swing.JLabel();
        lblHours = new javax.swing.JLabel();
        lblSecond = new javax.swing.JLabel();
        lblHours1 = new javax.swing.JLabel();
        lblHours2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Timesheet");
        setPreferredSize(new java.awt.Dimension(545, 516));

        jPanel1.setBackground(new java.awt.Color(204, 255, 255));

        lblLoggedInUser.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        lblLoggedInUser.setForeground(new java.awt.Color(0, 0, 204));
        lblLoggedInUser.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLoggedInUser.setToolTipText("Person who logged in");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel1.setText("-");

        btnAmendTimeSheet.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnAmendTimeSheet.setText("Amend timesheet");
        btnAmendTimeSheet.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnAmendTimeSheet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAmendTimeSheetActionPerformed(evt);
            }
        });

        txtDisplayUserTime.setEditable(false);

        lblMinute.setFont(new java.awt.Font("Digital dream", 1, 36)); // NOI18N
        lblMinute.setForeground(new java.awt.Color(102, 102, 255));
        lblMinute.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMinute.setText("00");
        lblMinute.setToolTipText("Running time");

        btnStopTimeSheet.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnStopTimeSheet.setText("Stop timesheet");
        btnStopTimeSheet.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnStopTimeSheet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStopTimeSheetActionPerformed(evt);
            }
        });

        lblStartTime.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblStartTime.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblStartTime.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lblStopTime.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblStopTime.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblStopTime.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lblHours.setFont(new java.awt.Font("Digital dream", 1, 36)); // NOI18N
        lblHours.setForeground(new java.awt.Color(102, 102, 255));
        lblHours.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHours.setText("00");
        lblHours.setToolTipText("Running time");

        lblSecond.setFont(new java.awt.Font("Digital dream", 1, 36)); // NOI18N
        lblSecond.setForeground(new java.awt.Color(102, 102, 255));
        lblSecond.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSecond.setText("00");
        lblSecond.setToolTipText("Running time");

        lblHours1.setFont(new java.awt.Font("Digital dream", 1, 36)); // NOI18N
        lblHours1.setForeground(new java.awt.Color(102, 102, 255));
        lblHours1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHours1.setText(":");
        lblHours1.setToolTipText("Running time");

        lblHours2.setFont(new java.awt.Font("Digital dream", 1, 36)); // NOI18N
        lblHours2.setForeground(new java.awt.Color(102, 102, 255));
        lblHours2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHours2.setText(":");
        lblHours2.setToolTipText("Running time");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lblLoggedInUser, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(121, 121, 121))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addComponent(lblHours)
                .addGap(18, 18, 18)
                .addComponent(lblHours1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblMinute)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblHours2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblSecond)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(txtDisplayUserTime, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnAmendTimeSheet, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(lblStartTime, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(36, 36, 36)
                            .addComponent(jLabel1)
                            .addGap(18, 18, 18)
                            .addComponent(lblStopTime, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.LEADING))
                    .addComponent(btnStopTimeSheet, javax.swing.GroupLayout.PREFERRED_SIZE, 478, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 480, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(lblLoggedInUser, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMinute, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSecond, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblHours, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblHours1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblHours2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblStartTime, javax.swing.GroupLayout.DEFAULT_SIZE, 51, Short.MAX_VALUE)
                    .addComponent(lblStopTime, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnStopTimeSheet, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAmendTimeSheet, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtDisplayUserTime, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jMenu1.setText("Exit");
        jMenu1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu1MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu1);

        jMenu2.setText("| About |");

        jMenu3.setText("Programmer");
        jMenu3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu3MouseClicked(evt);
            }
        });
        jMenu2.add(jMenu3);

        jMenu4.setText("Software");
        jMenu4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu4MouseClicked(evt);
            }
        });
        jMenu2.add(jMenu4);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenu1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu1MouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jMenu1MouseClicked

    private void jMenu3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu3MouseClicked
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Programmer: Banele Mlamleli\nGitHub: "+
            "https://github.com/BaneleMlamleli\nLinkedIn: www.linkedin.com/in/banele-mlamleli-a5b70980",
            "Programmer", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jMenu3MouseClicked

    private void jMenu4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu4MouseClicked
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Product Version: TimeSheet 1.0 (Build 201705191307)\n"+
            "IDE Info: NetBeans IDE 8.2 Patch 2\n"+
            "Java: 1.8.0_144; Java HotSpot(TM) 64-Bit Server VM 25.144-b01\n"+
            "Runtime: Java(TM) SE Runtime Environment 1.8.0_144-b01\n"+
            "System: Windows 10 version 10.0 running on amd64; Cp1252; en_ZA (nb)", "Software",
            JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jMenu4MouseClicked

    private void btnAmendTimeSheetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAmendTimeSheetActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new Details().setVisible(true);
    }//GEN-LAST:event_btnAmendTimeSheetActionPerformed

    private void btnStopTimeSheetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStopTimeSheetActionPerformed
        // TODO add your handling code here:
        //Add code for the reason why the user is stopping the time(activity)
        //state = false;
        String activity = JOptionPane.showInputDialog(null, "Reason for stopping time", "Activity", JOptionPane.INFORMATION_MESSAGE);
        String stopTime = hours+":"+minutes+":"+seconds;
        lblStopTime.setText(stopTime);
        txtDisplayUserTime.setText("\tStart time\t\tStop time\t\tActivity\n==============");//+
               // "\t\t==============\t\t==============\n"+startTime+"\t\t"+stopTime+"\t\t"+activity);
    }//GEN-LAST:event_btnStopTimeSheetActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TimeSheet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TimeSheet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TimeSheet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TimeSheet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TimeSheet().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAmendTimeSheet;
    private javax.swing.JButton btnStopTimeSheet;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lblHours;
    private javax.swing.JLabel lblHours1;
    private javax.swing.JLabel lblHours2;
    private javax.swing.JLabel lblLoggedInUser;
    private javax.swing.JLabel lblMinute;
    private javax.swing.JLabel lblSecond;
    private javax.swing.JLabel lblStartTime;
    private javax.swing.JLabel lblStopTime;
    private java.awt.TextField txtDisplayUserTime;
    // End of variables declaration//GEN-END:variables
}
