
package TimeSheet;

import javax.swing.*;
public class TimeSheet extends javax.swing.JFrame implements Runnable{
    
    Thread t;
    int hours = 0, minutes = 0, seconds = 0, microSeconds = 0;
    String str = "", nstr = "", mstr = "", dstr = "";
    int count = 0, count1 = 0;
    
    /**
     * Creates new form TimeSheet
     */
    public TimeSheet() {
        initComponents();
        t = new Thread(this);
        reset();
    }
    
    public void reset(){
        hours = 0; minutes = 0; seconds = 0; microSeconds = 0; count1 = 0;
        nstr = "00:00:00"; mstr = "000"; dstr = "";
        display();
    }
    
    public void display(){
        lblRunningTime.setText(nstr);
        lblRunningTimeMicroSec.setText(mstr);
    }
    
    public void setTimeCounter(){
        nstr = "";
        if(hours < 10){
            nstr = "0"+ hours;
        }else{
            nstr = ""+hours;
        }
        
        if(minutes < 10){
            nstr += ":0"+minutes;
        }else{
            nstr += ":"+minutes;
        }
        
        if(seconds < 10){
            nstr += ":0"+seconds;
        }else{
            nstr += ":"+seconds;
        }
    }
    
    public void setMTimeCounter(){
        mstr = "";
        if(minutes < 10){
            mstr = "00"+minutes;
        }else{
            if(minutes >= 10 && minutes < 100){
                mstr = "0"+minutes;
            }else{
                mstr = ""+minutes;
            }
        }
    }
    
    public void runTime(){
        try{
            while(true){
                minutes++;
                if(minutes > 999){
                    minutes = 0;
                    seconds++;
                }
                
                if(seconds > 59){
                    seconds = 0;
                    minutes++;
                }
                
                if(minutes > 59){
                    minutes = 0;
                    hours++;
                }
                        
                if(hours > 99){
                    reset();
                }
                
                setTimeCounter();
                setMTimeCounter();
                display();
                Thread.sleep(1);
            }
        }catch (Exception error){
            JOptionPane.showMessageDialog(null, "Error in runTime method","runTime method"+
                    error.getMessage(),JOptionPane.ERROR_MESSAGE);
        }
    }
    
    public void printToList(){
        count1++;
        dstr = "\n"+count1+") "+lblRunningTime.getText()+" "+
                lblRunningTimeMicroSec.getText()+"\n";
        txtDisplayUserTime.setText(dstr);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblLoggedInUser = new javax.swing.JLabel();
        lblRunningTimeMicroSec = new javax.swing.JLabel();
        txtEndTime = new javax.swing.JTextField();
        txtStartTime = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        btnStopTimeSheet = new javax.swing.JButton();
        btnAmendTimeSheet = new javax.swing.JButton();
        txtDisplayUserTime = new java.awt.TextField();
        lblRunningTime = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Timesheet");
        setPreferredSize(new java.awt.Dimension(545, 516));

        jPanel1.setBackground(new java.awt.Color(204, 255, 255));

        lblLoggedInUser.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        lblLoggedInUser.setForeground(new java.awt.Color(0, 0, 204));
        lblLoggedInUser.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLoggedInUser.setToolTipText("Person who logged in");

        lblRunningTimeMicroSec.setFont(new java.awt.Font("Digital dream", 1, 18)); // NOI18N
        lblRunningTimeMicroSec.setForeground(new java.awt.Color(102, 102, 255));
        lblRunningTimeMicroSec.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblRunningTimeMicroSec.setText("000");
        lblRunningTimeMicroSec.setToolTipText("Running time");

        txtEndTime.setEditable(false);
        txtEndTime.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        txtEndTime.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtEndTime.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        txtStartTime.setEditable(false);
        txtStartTime.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        txtStartTime.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtStartTime.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel1.setText("-");

        btnStopTimeSheet.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnStopTimeSheet.setText("Stop timesheet");
        btnStopTimeSheet.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnStopTimeSheet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStopTimeSheetActionPerformed(evt);
            }
        });

        btnAmendTimeSheet.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnAmendTimeSheet.setText("Amend timesheet");
        btnAmendTimeSheet.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnAmendTimeSheet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAmendTimeSheetActionPerformed(evt);
            }
        });

        txtDisplayUserTime.setEditable(false);

        lblRunningTime.setFont(new java.awt.Font("Digital dream", 1, 48)); // NOI18N
        lblRunningTime.setForeground(new java.awt.Color(102, 102, 255));
        lblRunningTime.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblRunningTime.setText("00:00:00");
        lblRunningTime.setToolTipText("Running time");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(btnStopTimeSheet, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnAmendTimeSheet, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(txtDisplayUserTime, javax.swing.GroupLayout.PREFERRED_SIZE, 505, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtStartTime)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(txtEndTime, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jSeparator1)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jSeparator2)
                        .addContainerGap())))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(lblRunningTime)
                        .addGap(18, 18, 18)
                        .addComponent(lblRunningTimeMicroSec)
                        .addGap(58, 58, 58))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(lblLoggedInUser, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(121, 121, 121))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(lblLoggedInUser, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRunningTime, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblRunningTimeMicroSec, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtStartTime, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtEndTime, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnStopTimeSheet, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAmendTimeSheet, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtDisplayUserTime, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jMenu1.setText("Exit");
        jMenu1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu1MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu1);

        jMenu2.setText("| About |");

        jMenu3.setText("Programmer");
        jMenu3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu3MouseClicked(evt);
            }
        });
        jMenu2.add(jMenu3);

        jMenu4.setText("Software");
        jMenu4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu4MouseClicked(evt);
            }
        });
        jMenu2.add(jMenu4);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnStopTimeSheetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStopTimeSheetActionPerformed
        // TODO add your handling code here:
        // JOptionPane.showMessageDialog(null, "Timesheet closed!", "Timesheet", JOptionPane.CLOSED_OPTION);
        if(btnStopTimeSheet.getText().equals("Stop timesheet")){
            btnStopTimeSheet.setText("Start timesheet");
            count++;
            if(count == 1){
                t.start();
            }else{
                t.resume();
            }
        }else{
            btnStopTimeSheet.setText("Stop timesheet");
            t.suspend();
            printToList();
        }       
    }//GEN-LAST:event_btnStopTimeSheetActionPerformed

    private void jMenu1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu1MouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jMenu1MouseClicked

    private void jMenu3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu3MouseClicked
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Programmer: Banele Mlamleli\nGitHub: "+
            "https://github.com/BaneleMlamleli\nLinkedIn: www.linkedin.com/in/banele-mlamleli-a5b70980",
            "Programmer", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jMenu3MouseClicked

    private void jMenu4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu4MouseClicked
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Product Version: TimeSheet 1.0 (Build 201705191307)\n"+
            "IDE Info: NetBeans IDE 8.2 Patch 2\n"+
            "Java: 1.8.0_144; Java HotSpot(TM) 64-Bit Server VM 25.144-b01\n"+
            "Runtime: Java(TM) SE Runtime Environment 1.8.0_144-b01\n"+
            "System: Windows 10 version 10.0 running on amd64; Cp1252; en_ZA (nb)", "Software",
            JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jMenu4MouseClicked

    private void btnAmendTimeSheetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAmendTimeSheetActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new Details().setVisible(true);
    }//GEN-LAST:event_btnAmendTimeSheetActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TimeSheet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TimeSheet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TimeSheet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TimeSheet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TimeSheet().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAmendTimeSheet;
    private javax.swing.JButton btnStopTimeSheet;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lblLoggedInUser;
    private javax.swing.JLabel lblRunningTime;
    private javax.swing.JLabel lblRunningTimeMicroSec;
    private java.awt.TextField txtDisplayUserTime;
    private javax.swing.JTextField txtEndTime;
    private javax.swing.JTextField txtStartTime;
    // End of variables declaration//GEN-END:variables
}
